using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Management;
using System.Net;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace KdnetHelper
{
    public partial class Form1 : Form
    {
        // Restore point P/Invoke
        [DllImport("srclient.dll")]
        private static extern int SRSetRestorePointA(ref RESTOREPOINTINFO pRestorePtSpec, ref STATEMGRSTATUS pSMgrStatus);

        [StructLayout(LayoutKind.Sequential)]
        private struct RESTOREPOINTINFO
        {
            public int dwEventType;
            public int dwRestorePtType;
            public long llSequenceNumber;
            public string szDescription;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct STATEMGRSTATUS
        {
            public int nStatus;
            public long llSequenceNumber;
        }

        private const int BEGIN_SYSTEM_CHANGE = 100;
        private const int END_SYSTEM_CHANGE = 101;
        private const int MODIFY_SETTINGS = 12;
        private const int APPLICATION_RUN = 20;

        // Redist paths
        private string _redistKdnetPath = null;
        private string _redistXmlDir = null;

        // Network share credentials
        private const string SHARE_USER = "KDNETHELPER";
        private const string SHARE_PASS = "KdnetH1!";
        private const string SHARE_FOLDER = "C:\\KDNETHELPERKEY";
        private const string SHARE_NAME = "KDNETHELPERKEY";
        private const string INI_FILE = "key.ini";

        // Tooltip helper
        private ToolTip _toolTip = new ToolTip();

        public Form1()
        {
            InitializeComponent();
            CheckAdminRights();
            SetupTooltips();
        }

        private void SetupTooltips()
        {
            // Target tab tooltips
            _toolTip.SetToolTip(lblTargetHostIp, "IP address of the HOST machine (the one running WinDbg). Used for KDNET setup.");
            _toolTip.SetToolTip(txtHostIp, "Enter the host machine's IPv4 address (e.g., 192.168.1.50).");
            _toolTip.SetToolTip(lblTargetPort, "KDNET port number. Recommended range: 50000-50039.");
            _toolTip.SetToolTip(txtPort, "Port for kernel debugging connection. Must match host's listening port.");
            _toolTip.SetToolTip(btnCheckNIC, "Checks if your network adapter supports KDNET kernel debugging.");
            _toolTip.SetToolTip(btnEnableKDNET, "Configures the target machine for KDNET and generates a debugging key.");
            _toolTip.SetToolTip(btnDisableDebug, "Disables kernel debugging on this machine. Requires reboot.");
            _toolTip.SetToolTip(btnCreateRestorePoint, "Create a system restore point before making changes (recommended).");
            _toolTip.SetToolTip(btnVerifyDebugSettings, "Shows current BCD debug settings, including the key if already configured.");
            _toolTip.SetToolTip(btnDisableBitLocker, "Completely disables BitLocker on the boot drive. You must re-enable it manually later.");
            _toolTip.SetToolTip(btnEnableBitLocker, "Re-enables BitLocker after debugging.");
            _toolTip.SetToolTip(btnDisableSecureBoot, "Reboots into UEFI firmware to disable Secure Boot.");
            _toolTip.SetToolTip(btnEnableSecureBoot, "Reboots into UEFI firmware to re-enable Secure Boot.");
            _toolTip.SetToolTip(lblTargetGeneratedKey, "The KDNET key used by the host to connect.");
            _toolTip.SetToolTip(txtGeneratedKey, "This key is automatically read from the system.");
            _toolTip.SetToolTip(chkShareKey, "Creates a network share with the key for automatic retrieval by the host. Requires admin rights.");
            _toolTip.SetToolTip(cmbTargetIPs, "");
            
            // Host tab tooltips
            _toolTip.SetToolTip(lblHostRef, "Your own host machine's IPv4 address (for reference only).");
            _toolTip.SetToolTip(cmbHostIPs, "");
            _toolTip.SetToolTip(btnRefreshIPs, "Re-scans and lists the host's IPv4 addresses.");
            _toolTip.SetToolTip(lblHostPort, "KDNET port number. Must match the port you entered on the target.");
            _toolTip.SetToolTip(txtHostPort, "Port on which WinDbg will listen for the target connection.");
            _toolTip.SetToolTip(lblHostKey, "The KDNET key generated by the target machine.");
            _toolTip.SetToolTip(txtHostKey, "Paste the key here, or use 'Fetch from Target' to retrieve via network share.");
            _toolTip.SetToolTip(btnLaunchWinDbg, "Launches WinDbg with the entered port and key, ready to debug the target.");
            _toolTip.SetToolTip(btnExportLog, "Saves the entire host debug log to a .txt file.");
            _toolTip.SetToolTip(txtTargetIP, "IP address of the target machine.");
            _toolTip.SetToolTip(btnFetchKey, "Attempts to read the key from the target.");
            _toolTip.SetToolTip(dgvDiscovered, "Displays machine name and key from the target.");
            _toolTip.SetToolTip(btnCopyKeyHost, "Copies the selected key to the clipboard and fills the key field.");
        }

        private void CheckAdminRights()
        {
            if (!IsAdministrator())
            {
                var result = MessageBox.Show(
                    "This tool requires administrator privileges to configure kernel debugging.\n\n" +
                    "Click OK to restart as Administrator, or Cancel to exit.",
                    "Administrator Required",
                    MessageBoxButtons.OKCancel,
                    MessageBoxIcon.Warning);

                if (result == DialogResult.OK)
                {
                    RestartAsAdmin();
                }
                else
                {
                    Environment.Exit(0);
                }
            }
        }

        private bool IsAdministrator()
        {
            using (var identity = System.Security.Principal.WindowsIdentity.GetCurrent())
            {
                var principal = new System.Security.Principal.WindowsPrincipal(identity);
                return principal.IsInRole(System.Security.Principal.WindowsBuiltInRole.Administrator);
            }
        }

        private void RestartAsAdmin()
        {
            var processInfo = new ProcessStartInfo
            {
                UseShellExecute = true,
                FileName = Application.ExecutablePath,
                Verb = "runas"
            };
            try
            {
                Process.Start(processInfo);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Unable to elevate: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            Environment.Exit(0);
        }

        #region Redist Detection

        private void CheckRedistFiles()
        {
            string arch = Environment.Is64BitOperatingSystem ? "x64" : "x86";
            string redistPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Redist", arch);

            string kdnetCandidate = Path.Combine(redistPath, "kdnet.exe");
            string xmlCandidate = Path.Combine(redistPath, "VerifiedNICList.xml");

            if (File.Exists(kdnetCandidate) && File.Exists(xmlCandidate))
            {
                _redistKdnetPath = kdnetCandidate;
                _redistXmlDir = redistPath;
                AppendLog("Target", $"Using redistributed KDNET files from: {redistPath}");
            }
            else
            {
                _redistKdnetPath = null;
                _redistXmlDir = null;
                AppendLog("Target", "Redistributed KDNET files not found. Will fallback to Windows SDK or manual selection.");
            }
        }

        private string FindKdnetPath(out string xmlDirectory)
        {
            if (_redistKdnetPath != null && _redistXmlDir != null)
            {
                xmlDirectory = _redistXmlDir;
                return _redistKdnetPath;
            }

            string[] possiblePaths = {
                @"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\kdnet.exe",
                @"C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\kdnet.exe",
                @"C:\Program Files\Windows Kits\10\Debuggers\x64\kdnet.exe",
                @"C:\Program Files\Windows Kits\10\Debuggers\x86\kdnet.exe"
            };

            foreach (var path in possiblePaths)
            {
                if (File.Exists(path))
                {
                    xmlDirectory = Path.GetDirectoryName(path);
                    return path;
                }
            }

            using (var dialog = new OpenFileDialog())
            {
                dialog.Title = "Locate kdnet.exe";
                dialog.Filter = "kdnet.exe|kdnet.exe";
                dialog.FileName = "kdnet.exe";
                if (dialog.ShowDialog() == DialogResult.OK)
                {
                    xmlDirectory = Path.GetDirectoryName(dialog.FileName);
                    return dialog.FileName;
                }
            }

            xmlDirectory = null;
            return null;
        }

        #endregion

        #region BitLocker & Secure Boot Helpers

        private string GetBootDrive()
        {
            string bootDrive = Environment.GetEnvironmentVariable("SystemDrive");
            if (string.IsNullOrEmpty(bootDrive))
                bootDrive = "C:";
            return bootDrive;
        }

        private bool IsBitLockerEnabled()
        {
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "manage-bde",
                    Arguments = "-status C:",
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (var proc = Process.Start(psi))
                {
                    string output = proc.StandardOutput.ReadToEnd();
                    proc.WaitForExit();
                    return output.Contains("Protection On") || output.Contains("Protection Status: On");
                }
            }
            catch
            {
                return false;
            }
        }

        private void DisableBitLocker()
        {
            string bootDrive = GetBootDrive();
            var result = MessageBox.Show(
                $"This will fully disable BitLocker on drive {bootDrive}.\n\n" +
                "After you finish debugging, you must manually re-enable BitLocker using:\n" +
                "  Manage-bde -protectors -enable {drive}:\n" +
                "or via the BitLocker Control Panel.\n\n" +
                "Do you want to continue?",
                "Disable BitLocker",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning);

            if (result != DialogResult.Yes)
                return;

            AppendLog("Target", $"Disabling BitLocker on {bootDrive}... (this may take a while)");

            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "powershell",
                    Arguments = $"-Command \"Disable-BitLocker -MountPoint '{bootDrive}'\"",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (var proc = Process.Start(psi))
                {
                    string output = proc.StandardOutput.ReadToEnd();
                    string error = proc.StandardError.ReadToEnd();
                    proc.WaitForExit();
                    if (proc.ExitCode == 0)
                    {
                        AppendLog("Target", $"BitLocker disabled on {bootDrive}.");
                        MessageBox.Show($"BitLocker has been disabled on {bootDrive}.\n\n" +
                                        "To re-enable later, click 'Re-enable BitLocker' button or use Control Panel.",
                                        "BitLocker Disabled",
                                        MessageBoxButtons.OK,
                                        MessageBoxIcon.Information);
                    }
                    else
                    {
                        AppendLog("Target", $"Failed to disable BitLocker: {error}{output}");
                        MessageBox.Show($"Error disabling BitLocker:\n{error}{output}", "BitLocker Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
            catch (Exception ex)
            {
                AppendLog("Target", $"Exception disabling BitLocker: {ex.Message}");
                MessageBox.Show($"Exception: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void EnableBitLocker()
        {
            if (IsSecureBootEnabled())
            {
                var sbResult = MessageBox.Show(
                    "Secure Boot is currently enabled.\n\n" +
                    "BitLocker can be re-enabled with Secure Boot on. This is the normal configuration.\n\n" +
                    "Do you want to proceed with enabling BitLocker?",
                    "Secure Boot Detected",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question);
                if (sbResult != DialogResult.Yes)
                    return;
            }
            else
            {
                var sbResult = MessageBox.Show(
                    "Secure Boot is NOT enabled.\n\n" +
                    "BitLocker can still be enabled, but it may be less secure.\n\n" +
                    "Do you want to continue?",
                    "Secure Boot Disabled",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Warning);
                if (sbResult != DialogResult.Yes)
                    return;
            }

            string bootDrive = GetBootDrive();
            AppendLog("Target", $"Re-enabling BitLocker on {bootDrive}... (this may take several minutes)");

            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "powershell",
                    Arguments = $"-Command \"Enable-BitLocker -MountPoint '{bootDrive}' -SkipHardwareTest\"",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (var proc = Process.Start(psi))
                {
                    string output = proc.StandardOutput.ReadToEnd();
                    string error = proc.StandardError.ReadToEnd();
                    proc.WaitForExit();
                    if (proc.ExitCode == 0)
                    {
                        AppendLog("Target", $"BitLocker re-enabled on {bootDrive}.");
                        MessageBox.Show($"BitLocker has been re-enabled on {bootDrive}.", "BitLocker Enabled", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                    else
                    {
                        AppendLog("Target", $"Failed to enable BitLocker: {error}{output}");
                        MessageBox.Show($"Error enabling BitLocker:\n{error}{output}", "BitLocker Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
            catch (Exception ex)
            {
                AppendLog("Target", $"Exception enabling BitLocker: {ex.Message}");
                MessageBox.Show($"Exception: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private bool IsSecureBootEnabled()
        {
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "powershell",
                    Arguments = "-Command \"Confirm-SecureBootUEFI\"",
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (var proc = Process.Start(psi))
                {
                    string output = proc.StandardOutput.ReadToEnd().Trim();
                    proc.WaitForExit();
                    return output.Equals("True", StringComparison.OrdinalIgnoreCase);
                }
            }
            catch
            {
                return false;
            }
        }

        private void DisableSecureBoot()
        {
            var result = MessageBox.Show(
                "Disabling Secure Boot requires a reboot into UEFI firmware settings.\n\n" +
                "After reboot, navigate to the Secure Boot option and set it to 'Disabled'.\n" +
                "Save changes and exit.\n\n" +
                "Do you want to restart now to access UEFI settings?",
                "Disable Secure Boot",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Information);

            if (result == DialogResult.Yes)
            {
                AppendLog("Target", "Restarting into UEFI firmware settings in 10 seconds... Please disable Secure Boot manually.");
                Process.Start("shutdown", "/r /fw /t 10 /c \"Restarting to UEFI firmware. Please disable Secure Boot.\"");
            }
        }

        private void EnableSecureBoot()
        {
            var result = MessageBox.Show(
                "Enabling Secure Boot requires a reboot into UEFI firmware settings.\n\n" +
                "After reboot, navigate to the Secure Boot option and set it to 'Enabled'.\n" +
                "Save changes and exit.\n\n" +
                "Do you want to restart now to access UEFI settings?",
                "Enable Secure Boot",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Information);

            if (result == DialogResult.Yes)
            {
                AppendLog("Target", "Restarting into UEFI firmware settings in 10 seconds... Please enable Secure Boot manually.");
                Process.Start("shutdown", "/r /fw /t 10 /c \"Restarting to UEFI firmware. Please enable Secure Boot.\"");
            }
        }

        #endregion

        #region Network Share Key Management (Target Side)

        private void RunCommandAndLog(string command, string arguments, out string output, out string error)
        {
            output = "";
            error = "";
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = command,
                    Arguments = arguments,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (var proc = Process.Start(psi))
                {
                    output = proc.StandardOutput.ReadToEnd();
                    error = proc.StandardError.ReadToEnd();
                    proc.WaitForExit();
                }
            }
            catch (Exception ex)
            {
                error = ex.Message;
            }
        }

        private void RunCommandWithTimeout(string command, string arguments, int timeoutMilliseconds)
        {
            var psi = new ProcessStartInfo
            {
                FileName = command,
                Arguments = arguments,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using (var proc = Process.Start(psi))
            {
                if (proc != null)
                {
                    if (!proc.WaitForExit(timeoutMilliseconds))
                    {
                        proc.Kill();
                        throw new TimeoutException($"Command '{command} {arguments}' timed out after {timeoutMilliseconds} ms");
                    }
                    string error = proc.StandardError.ReadToEnd();
                    if (!string.IsNullOrEmpty(error))
                        AppendLog("Target", $"Command warning: {error}");
                }
            }
        }

        private string GetLocalIPv4()
        {
            if (cmbTargetIPs.SelectedItem != null && cmbTargetIPs.SelectedItem.ToString() != "No IPv4 address")
                return cmbTargetIPs.SelectedItem.ToString();
            var ip = NetworkInterface.GetAllNetworkInterfaces()
                .Where(nic => nic.OperationalStatus == OperationalStatus.Up && nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
                .SelectMany(nic => nic.GetIPProperties().UnicastAddresses)
                .FirstOrDefault(addr => addr.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);
            return ip?.Address.ToString() ?? "unknown";
        }

        private bool IsShareReady()
        {
            if (!Directory.Exists(SHARE_FOLDER)) return false;
            if (!File.Exists(Path.Combine(SHARE_FOLDER, INI_FILE))) return false;
            var psi = new ProcessStartInfo
            {
                FileName = "net",
                Arguments = "share",
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using (var proc = Process.Start(psi))
            {
                string output = proc.StandardOutput.ReadToEnd();
                if (!output.Contains(SHARE_NAME)) return false;
            }
            psi = new ProcessStartInfo
            {
                FileName = "net",
                Arguments = $"user {SHARE_USER}",
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using (var proc = Process.Start(psi))
            {
                string output = proc.StandardOutput.ReadToEnd();
                if (!output.Contains(SHARE_USER)) return false;
            }
            string iniPath = Path.Combine(SHARE_FOLDER, INI_FILE);
            if (File.Exists(iniPath))
            {
                var lines = File.ReadAllLines(iniPath);
                foreach (var line in lines)
                {
                    if (line.StartsWith("Key="))
                    {
                        string savedKey = line.Substring(4);
                        if (savedKey == txtGeneratedKey.Text)
                            return true;
                    }
                }
            }
            return false;
        }

        private async Task CleanupShareAsync()
        {
            AppendLog("Target", "Cleaning up network share...");
            await Task.Run(() => RunCommandWithTimeout("schtasks", "/delete /tn \"KDNETHELPER_Cleanup\" /f", 10000));
            await Task.Run(() => RunCommandWithTimeout("net", $"share {SHARE_NAME} /delete", 10000));
            if (Directory.Exists(SHARE_FOLDER))
            {
                try { Directory.Delete(SHARE_FOLDER, true); }
                catch (Exception ex) { AppendLog("Target", $"Failed to delete folder: {ex.Message}"); }
            }
            await Task.Run(() => RunCommandWithTimeout("net", $"user {SHARE_USER} /delete", 10000));
            AppendLog("Target", "Cleanup completed.");
        }

        private async Task CreateShareAsync()
        {
            AppendLog("Target", "Setting up network share for key...");
            try
            {
                await Task.Run(() => RunCommandWithTimeout("net", $"user {SHARE_USER} {SHARE_PASS} /add /fullname:\"KDNET Helper\"", 10000));
                if (!Directory.Exists(SHARE_FOLDER))
                    Directory.CreateDirectory(SHARE_FOLDER);
                string iniPath = Path.Combine(SHARE_FOLDER, INI_FILE);
                await File.WriteAllTextAsync(iniPath, $"MachineName={Environment.MachineName}\r\nKey={txtGeneratedKey.Text}\r\nCreated={DateTime.Now}");
                await Task.Run(() => RunCommandWithTimeout("icacls", $"{SHARE_FOLDER} /grant {SHARE_USER}:(OI)(CI)F /T", 30000));
                await Task.Run(() => RunCommandWithTimeout("net", $"share {SHARE_NAME}={SHARE_FOLDER} /GRANT:{SHARE_USER},FULL", 10000));
                
                // PowerShell one-liner scheduled task for cleanup
                string psCommand = $@"
    $logFile = '{SHARE_FOLDER}\\cleanup.log'
    Add-Content $logFile -Value ""$(Get-Date) - Cleaning up KDNETHELPER share...""
    try {{
        net share {SHARE_NAME} /delete >> $logFile 2>&1
        Remove-Item -Path '{SHARE_FOLDER}' -Recurse -Force -ErrorAction SilentlyContinue
        net user {SHARE_USER} /delete >> $logFile 2>&1
        schtasks /delete /tn ""KDNETHELPER_Cleanup"" /f >> $logFile 2>&1
        Add-Content $logFile -Value ""$(Get-Date) - Cleanup completed successfully.""
    }} catch {{
        Add-Content $logFile -Value ""$(Get-Date) - Error: $_""
    }}
";
                psCommand = psCommand.Replace("\"", "\\\"");
                string taskArgs = $"-Command \"{psCommand}\"";
                string createTaskCmd = $"/create /tn \"KDNETHELPER_Cleanup\" /tr \"powershell.exe -ExecutionPolicy Bypass {taskArgs}\" /sc ONSTART /ru SYSTEM /f";
                await Task.Run(() => RunCommandWithTimeout("schtasks", createTaskCmd, 10000));
                
                AppendLog("Target", "Share created successfully. Cleanup scheduled on next boot (logs: " + SHARE_FOLDER + "\\cleanup.log).");
                MessageBox.Show($"Network share created successfully.\n\nFolder: {SHARE_FOLDER}\nShare: \\\\{GetLocalIPv4()}\\{SHARE_NAME}\nUser: {SHARE_USER}\n\nThe key will be automatically removed on next system restart.", "Share Created", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                AppendLog("Target", $"Error creating share: {ex.Message}");
                MessageBox.Show($"Failed to create share: {ex.Message}", "Share Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                throw;
            }
        }

        private void PopulateTargetIPs()
        {
            cmbTargetIPs.Items.Clear();
            var ips = NetworkInterface.GetAllNetworkInterfaces()
                .Where(nic => nic.OperationalStatus == OperationalStatus.Up && nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
                .SelectMany(nic => nic.GetIPProperties().UnicastAddresses)
                .Where(addr => addr.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
                .Select(addr => addr.Address.ToString())
                .Distinct()
                .ToList();
            if (ips.Count == 0)
                cmbTargetIPs.Items.Add("No IPv4 address");
            else
                cmbTargetIPs.Items.AddRange(ips.ToArray());
            if (cmbTargetIPs.Items.Count > 0)
                cmbTargetIPs.SelectedIndex = 0;
        }

        #endregion

        #region Host Tab - Read Key from Target Share

        private string ReadKeyFromTargetShare(string targetIP)
        {
            string uncPath = $@"\\{targetIP}\{SHARE_NAME}\{INI_FILE}";
            string localFile = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + ".ini");
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "net",
                    Arguments = $"use \\\\{targetIP}\\{SHARE_NAME} /user:{SHARE_USER} {SHARE_PASS}",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using (var proc = Process.Start(psi))
                {
                    proc.WaitForExit();
                    if (proc.ExitCode != 0)
                    {
                        string err = proc.StandardError.ReadToEnd();
                        AppendLog("Host", $"Net use failed: {err}");
                        return null;
                    }
                }
                File.Copy(uncPath, localFile, true);
                var lines = File.ReadAllLines(localFile);
                foreach (var line in lines)
                {
                    if (line.StartsWith("Key="))
                        return line.Substring(4);
                }
                return null;
            }
            catch (Exception ex)
            {
                AppendLog("Host", $"Error reading key from share: {ex.Message}");
                return null;
            }
            finally
            {
                RunCommandAndLog("net", $"use \\\\{targetIP}\\{SHARE_NAME} /delete", out _, out _);
                if (File.Exists(localFile)) File.Delete(localFile);
            }
        }

        #endregion

        #region Target Tab Event Handlers

        private void btnCheckNIC_Click(object sender, EventArgs e)
        {
            string kdnetPath = FindKdnetPath(out string xmlDir);
            if (kdnetPath == null)
            {
                AppendLog("Target", "kdnet.exe not found. Please ensure Windows SDK/Debugging Tools are installed or place files in Redist folder.");
                return;
            }

            AppendLog("Target", $"Checking NIC compatibility using {kdnetPath}...");
            RunCommandAndLog(kdnetPath, "", out string output, out string error);
            if (!string.IsNullOrEmpty(output))
                AppendLog("Target", output);
            if (!string.IsNullOrEmpty(error))
                AppendLog("Target", "ERROR: " + error);
        }

        private void btnEnableKDNET_Click(object sender, EventArgs e)
        {
            string hostIp = txtHostIp.Text.Trim();
            if (!IPAddress.TryParse(hostIp, out _))
            {
                MessageBox.Show("Enter a valid Host IP address (e.g., 192.168.1.50)", "Invalid IP", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            if (!int.TryParse(txtPort.Text, out int port) || port < 1 || port > 65535)
            {
                MessageBox.Show("Enter a valid port number (1-65535). Recommended: 50000-50039", "Invalid Port", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            string kdnetPath = FindKdnetPath(out string sourceDir);
            if (kdnetPath == null)
            {
                AppendLog("Target", "Cannot enable KDNET: kdnet.exe not found.");
                return;
            }

            string workDir = @"C:\KDNET";
            if (!Directory.Exists(workDir))
                Directory.CreateDirectory(workDir);

            string destKdnet = Path.Combine(workDir, "kdnet.exe");
            string sourceXml = Path.Combine(sourceDir, "VerifiedNICList.xml");
            string destXml = Path.Combine(workDir, "VerifiedNICList.xml");

            if (!File.Exists(destKdnet))
                File.Copy(kdnetPath, destKdnet, true);
            if (File.Exists(sourceXml) && !File.Exists(destXml))
                File.Copy(sourceXml, destXml, true);
            else if (!File.Exists(sourceXml))
                AppendLog("Target", "Warning: VerifiedNICList.xml not found in source directory. KDNET may fail.");

            AppendLog("Target", $"Running kdnet {hostIp} {port} ...");
            RunCommandAndLog(destKdnet, $"{hostIp} {port}", out string output, out string error);
            AppendLog("Target", output);
            if (!string.IsNullOrEmpty(error))
                AppendLog("Target", "ERROR: " + error);

            Regex keyRegex = new Regex(@"([A-Za-z0-9]+(?:\.[A-Za-z0-9]+){3})");
            Match match = keyRegex.Match(output);
            if (match.Success)
            {
                string key = match.Value;
                AppendLog("Target", $"*** Generated Key: {key} ***");
                MessageBox.Show($"Key generated:\n{key}\n\nCopy this key to the Host machine.", "KDNET Key", MessageBoxButtons.OK, MessageBoxIcon.Information);
                txtGeneratedKey.Text = key;
            }

            AppendLog("Target", "Enabling kernel debugging in BCD...");
            RunCommandAndLog("bcdedit", "/set {default} debug yes", out _, out string bcdError);
            if (!string.IsNullOrEmpty(bcdError))
                AppendLog("Target", "bcdedit error: " + bcdError);
            else
                AppendLog("Target", "Kernel debugging enabled successfully. Reboot the target machine to start debugging.");
        }

        private void btnDisableDebug_Click(object sender, EventArgs e)
        {
            AppendLog("Target", "Disabling kernel debugging...");

            // Turn off debug flag
            RunCommandAndLog("bcdedit", "/debug off", out string output1, out string error1);
            AppendLog("Target", output1);
            if (!string.IsNullOrEmpty(error1))
                AppendLog("Target", "Error (debug off): " + error1);

            // Remove debug value (may not exist, ignore)
            RunCommandAndLog("bcdedit", "/deletevalue {default} debug", out _, out string error2);
            if (!string.IsNullOrEmpty(error2) && !error2.Contains("not found"))
                AppendLog("Target", "Note: " + error2);

            // Clear all global KDNET settings from {dbgsettings}
            AppendLog("Target", "Clearing global KDNET settings...");
            RunCommandAndLog("bcdedit", "/deletevalue {dbgsettings} key", out _, out string errKey);
            RunCommandAndLog("bcdedit", "/deletevalue {dbgsettings} hostip", out _, out _);
            RunCommandAndLog("bcdedit", "/deletevalue {dbgsettings} port", out _, out _);
            RunCommandAndLog("bcdedit", "/deletevalue {dbgsettings} dhcp", out _, out _);
            RunCommandAndLog("bcdedit", "/deletevalue {dbgsettings} debugtype", out _, out _);
            
            if (!string.IsNullOrEmpty(errKey) && !errKey.Contains("not found"))
                AppendLog("Target", "Error clearing key: " + errKey);

            AppendLog("Target", "Debugging disabled. Reboot to return to normal operation.");
        }

        private void btnCreateRestorePoint_Click(object sender, EventArgs e)
        {
            AppendLog("Target", "Creating system restore point...");
            bool success = CreateRestorePoint("Before KDNET Setup - " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
            if (success)
                AppendLog("Target", "Restore point created successfully.");
            else
                AppendLog("Target", "Failed to create restore point (may be disabled or not supported).");
        }

        private bool CreateRestorePoint(string description)
        {
            try
            {
                using (var managementClass = new ManagementClass("\\\\.\\root\\default", "SystemRestore", null))
                {
                    var results = managementClass.GetMethodParameters("CreateRestorePoint");
                    results["Description"] = description;
                    results["RestorePointType"] = MODIFY_SETTINGS;
                    results["EventType"] = BEGIN_SYSTEM_CHANGE;
                    var outParams = managementClass.InvokeMethod("CreateRestorePoint", results, null);
                    return (uint)outParams["ReturnValue"] == 0;
                }
            }
            catch
            {
                try
                {
                    var psi = new ProcessStartInfo
                    {
                        FileName = "powershell",
                        Arguments = $"-Command \"Checkpoint-Computer -Description '{description}' -RestorePointType MODIFY_SETTINGS\"",
                        UseShellExecute = false,
                        CreateNoWindow = true
                    };
                    using (var proc = Process.Start(psi))
                    {
                        proc.WaitForExit();
                        return proc.ExitCode == 0;
                    }
                }
                catch
                {
                    return false;
                }
            }
        }

        private void btnVerifyDebugSettings_Click(object sender, EventArgs e)
        {
            AppendLog("Target", "Current debug settings:");
            RunCommandAndLog("bcdedit", "/dbgsettings", out string output, out string error);
            AppendLog("Target", output);
            if (!string.IsNullOrEmpty(error))
                AppendLog("Target", "Error: " + error);
        }

        private void btnDisableBitLocker_Click(object sender, EventArgs e)
        {
            if (!IsBitLockerEnabled())
            {
                MessageBox.Show("BitLocker does not appear to be enabled on the boot drive.", "BitLocker Status", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            DisableBitLocker();
        }

        private void btnEnableBitLocker_Click(object sender, EventArgs e)
        {
            if (IsBitLockerEnabled())
            {
                MessageBox.Show("BitLocker is already enabled.", "BitLocker Status", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            EnableBitLocker();
        }

        private void btnDisableSecureBoot_Click(object sender, EventArgs e)
        {
            DisableSecureBoot();
        }

        private void btnEnableSecureBoot_Click(object sender, EventArgs e)
        {
            EnableSecureBoot();
        }

        private void LoadCurrentDebugSettings()
        {
            AppendLog("Target", "Loading current debug settings...");
            RunCommandAndLog("bcdedit", "/dbgsettings", out string output, out string error);
            if (!string.IsNullOrEmpty(output))
            {
                var lines = output.Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries);
                foreach (var line in lines)
                {
                    if (line.Trim().StartsWith("key", StringComparison.OrdinalIgnoreCase))
                    {
                        var parts = line.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                        if (parts.Length >= 2)
                        {
                            string key = parts[1];
                            txtGeneratedKey.Text = key;
                            AppendLog("Target", $"Found existing key: {key}");
                            break;
                        }
                    }
                }
            }
            else if (!string.IsNullOrEmpty(error))
            {
                AppendLog("Target", "Could not read debug settings: " + error);
            }
        }

        private async void chkShareKey_CheckedChanged(object sender, EventArgs e)
        {
            if (chkShareKey.Checked)
            {
                if (string.IsNullOrEmpty(txtGeneratedKey.Text))
                {
                    MessageBox.Show("No KDNET key available to share.", "Cannot Share", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    chkShareKey.Checked = false;
                    return;
                }
                if (IsShareReady())
                {
                    AppendLog("Target", "Share already exists and is up-to-date.");
                    return;
                }
                chkShareKey.Enabled = false;
                try
                {
                    await CreateShareAsync();
                }
                catch
                {
                    chkShareKey.Checked = false;
                }
                finally
                {
                    chkShareKey.Enabled = true;
                }
            }
            else
            {
                await CleanupShareAsync();
            }
        }

        #endregion

        #region Host Tab Event Handlers

        private void PopulateLocalIPs()
        {
            cmbHostIPs.Items.Clear();
            var ips = NetworkInterface.GetAllNetworkInterfaces()
                .Where(nic => nic.OperationalStatus == OperationalStatus.Up && nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
                .SelectMany(nic => nic.GetIPProperties().UnicastAddresses)
                .Where(addr => addr.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
                .Select(addr => addr.Address.ToString())
                .Distinct()
                .ToList();

            if (ips.Count == 0)
            {
                cmbHostIPs.Items.Add("No IPv4 address found");
            }
            else
            {
                foreach (var ip in ips)
                    cmbHostIPs.Items.Add(ip);
                if (cmbHostIPs.Items.Count > 0)
                    cmbHostIPs.SelectedIndex = 0;
            }
        }

        private string FindWinDbgPath()
        {
            string[] possiblePaths = {
                @"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe",
                @"C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\windbg.exe",
                @"C:\Program Files\Windows Kits\10\Debuggers\x64\windbg.exe",
                @"C:\Program Files\Windows Kits\10\Debuggers\x86\windbg.exe"
            };
            foreach (var path in possiblePaths)
            {
                if (File.Exists(path))
                    return path;
            }
            var which = Which("windbg.exe");
            if (which != null)
                return which;
            return null;
        }

        private string Which(string cmd)
        {
            var paths = Environment.GetEnvironmentVariable("PATH").Split(Path.PathSeparator);
            foreach (var path in paths)
            {
                var fullPath = Path.Combine(path, cmd);
                if (File.Exists(fullPath))
                    return fullPath;
            }
            return null;
        }

        private void btnLaunchWinDbg_Click(object sender, EventArgs e)
        {
            string port = txtHostPort.Text.Trim();
            string key = txtHostKey.Text.Trim();

            if (string.IsNullOrEmpty(port) || !int.TryParse(port, out _))
            {
                MessageBox.Show("Enter a valid port number.", "Missing Port", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            if (string.IsNullOrEmpty(key) || !Regex.IsMatch(key, @"^[A-Za-z0-9]+(\.[A-Za-z0-9]+){3}$"))
            {
                MessageBox.Show("Enter a valid KDNET key (four alphanumeric segments separated by dots).", "Invalid Key", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            string windbg = FindWinDbgPath();
            if (windbg == null)
            {
                MessageBox.Show("WinDbg not found. Please install Windows SDK/Debugging Tools.", "Missing WinDbg", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            string args = $"-k net:port={port},key={key}";
            AppendLog("Host", $"Launching: {windbg} {args}");
            try
            {
                Process.Start(new ProcessStartInfo { FileName = windbg, Arguments = args, UseShellExecute = true });
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to launch WinDbg: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnRefreshIPs_Click(object sender, EventArgs e)
        {
            PopulateLocalIPs();
        }

        private void btnExportLog_Click(object sender, EventArgs e)
        {
            using (SaveFileDialog sfd = new SaveFileDialog())
            {
                sfd.Filter = "Text Files (*.txt)|*.txt|All Files (*.*)|*.*";
                sfd.DefaultExt = "txt";
                sfd.FileName = $"KDNET_Debug_Log_{DateTime.Now:yyyyMMdd_HHmmss}.txt";
                if (sfd.ShowDialog() == DialogResult.OK)
                {
                    try
                    {
                        File.WriteAllText(sfd.FileName, txtHostLog.Text);
                        MessageBox.Show($"Log exported successfully to:\n{sfd.FileName}", "Export Complete", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        AppendLog("Host", $"Exported log to {sfd.FileName}");
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show($"Failed to export log: {ex.Message}", "Export Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
        }

        private void btnFetchKey_Click(object sender, EventArgs e)
        {
            string targetIP = txtTargetIP.Text.Trim();
            if (string.IsNullOrEmpty(targetIP))
            {
                MessageBox.Show("Enter the target machine's IP address.", "Missing IP", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            AppendLog("Host", $"Attempting to fetch key from {targetIP}...");
            string key = ReadKeyFromTargetShare(targetIP);
            if (!string.IsNullOrEmpty(key))
            {
                dgvDiscovered.Rows.Add(Environment.MachineName, key);
                AppendLog("Host", $"Key retrieved successfully: {key}");
                MessageBox.Show($"Key retrieved from target:\n{key}", "Key Retrieved", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                AppendLog("Host", "Failed to retrieve key. Ensure share is active and network accessible.");
                MessageBox.Show("Could not retrieve key. Check that the target has shared the key and you have network access.", "Retrieval Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCopyKeyHost_Click(object sender, EventArgs e)
        {
            if (dgvDiscovered.SelectedRows.Count > 0)
            {
                string key = dgvDiscovered.SelectedRows[0].Cells["KeyColumn"].Value?.ToString();
                if (!string.IsNullOrEmpty(key))
                {
                    Clipboard.SetText(key);
                    txtHostKey.Text = key;
                    MessageBox.Show("Key copied to clipboard and filled in field.", "Copied", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            else
            {
                MessageBox.Show("Select a row first.", "No Selection", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        #endregion

        #region Logging and Form Events

        private void ScrollToBottom(RichTextBox richTextBox)
        {
            if (richTextBox.InvokeRequired)
            {
                richTextBox.Invoke(new Action(() => ScrollToBottom(richTextBox)));
                return;
            }
            richTextBox.SelectionStart = richTextBox.TextLength;
            richTextBox.ScrollToCaret();
            richTextBox.Refresh();
        }

        private void AppendLog(string tab, string message)
        {
            if (tab == "Target" && txtTargetLog.InvokeRequired)
            {
                txtTargetLog.Invoke(new Action(() => AppendLog(tab, message)));
                return;
            }
            if (tab == "Host" && txtHostLog.InvokeRequired)
            {
                txtHostLog.Invoke(new Action(() => AppendLog(tab, message)));
                return;
            }
            string timestamp = DateTime.Now.ToString("HH:mm:ss");
            string line = $"[{timestamp}] {message}{Environment.NewLine}";
            if (tab == "Target")
            {
                txtTargetLog.AppendText(line);
                if (chkTargetAutoScroll != null && chkTargetAutoScroll.Checked)
                    ScrollToBottom(txtTargetLog);
            }
            else if (tab == "Host")
            {
                txtHostLog.AppendText(line);
                if (chkHostAutoScroll != null && chkHostAutoScroll.Checked)
                    ScrollToBottom(txtHostLog);
            }
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            CheckRedistFiles();
            PopulateLocalIPs();
            LoadCurrentDebugSettings();
            PopulateTargetIPs();
            // Setup DataGridView on host tab
            dgvDiscovered.AutoGenerateColumns = false;
            dgvDiscovered.Columns.Clear();
            dgvDiscovered.Columns.Add(new DataGridViewTextBoxColumn { Name = "MachineColumn", HeaderText = "Machine Name", DataPropertyName = "Machine", Width = 200 });
            dgvDiscovered.Columns.Add(new DataGridViewTextBoxColumn { Name = "KeyColumn", HeaderText = "Key", DataPropertyName = "Key", Width = 300 });
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            AppendLog("Target", "Application closing. Share cleanup scheduled on next boot if not already cleaned.");
        }

        #endregion
    }
}